import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Insets;
import java.awt.event.MouseEvent;
import java.io.Serializable;

import javax.swing.border.Border;


/**
 * @author smvorwerk
 *
 */
public class ResizeBorder implements Border, Serializable {

	/**
	 * default serialVersionUID generated by eclipse
	 */
	private static final long serialVersionUID = 1L;
	private Color color;
	
	/**
	 * @param c
	 */
	public ResizeBorder(Color c) {
		this.color = c;
	}
	/**
	 * 
	 */
	public ResizeBorder() {
		this.color = Color.black;
	}
	@Override
	public Insets getBorderInsets(Component c) {
		return new Insets(5, 5, 6, 6);
	}

	@Override
	public boolean isBorderOpaque() {
		// TODO Auto-generated method stub
		return true;
	}

	@Override
	public void paintBorder(Component c, Graphics g, int x, int y, int width,
			int height) {
		
		g.setColor(color);
		
		//draw lines around the component
		g.fillRect(x, y, width, 1);
		g.fillRect(x, y+height-1, width, 1);
		g.fillRect(x+width-1, y, 1, height);
		g.fillRect(x, y, 1, height);
		
		//now draw anchor rectangles
		g.fillRect(x, y, 5, 5);
		g.fillRect(x+width-6, y, 5, 5);
		g.fillRect(x, y+height-6, 5, 5);
		g.fillRect(x+width-6, y+height-6, 5, 5);
		
	}
	
	
}
